name: MERN CI

on:
  push:
    branches: [main]

jobs:
  mongo-init:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports: ['27017:27017']

    steps:
      - name: checkout repository
        uses: actions/checkout@v5
      
      - name: setup nodej
        uses: actions/setup-node@v3
        with:
          node-vserion: '18'

      - name: Waiting for mongodb to be ready
        run: |
          until nc -z localhost 27017; do
            echo "waiting for mongodb"
            sleep 2
          done
            echo "mongodb is up"
      
      - name: Seed mongodb
        working-directory: ./backend
        run: |
          npm install
          node seedTaskData.js

  test:
    runs-on: ubuntu-latest
    needs: mongo-init

    steps:
      - name: checkout repository
        uses: actions/checkout@v5
      
      - name: setup nodej
        uses: actions/setup-node@v3
        with:
          node-vserion: '18'
      
      - name: Install dependencies for backend
        working-directory: ./backend
        run: npm install
      
      - name: running backend tests
        working-directory: ./backend
        run: npm test


